### PR TITLE
Update theme to handle blog section

### LINKED ISSUE #8: Add a RSS feed
One of the biggest complaint is… there is no RSS feed to follow releases of FRSS on freshrss.org. In a first time, it could be great to add https://github.com/FreshRSS/FreshRSS/releases.atom stream but a real feed could be great (but it means we'll have to feed it)

### LINKED ISSUE #10: Add a blog (Pelican)
Actually, there is no blog! We need one!

I'm working with Pelican which is a great tool static site generator. Advantage is we will be able to store articles in a Git repository easily (Markdown format) and so having an open writing process.

I'm trying to port the actual website on Pelican so we can integrate the blog easily.

Should fix #8

### PR DESCRIPTION
**Pull request by marienfressinaud**
Design has been updated a lot but keep the same "philosophy".

To have a look to the new design, please have a look to http://dev.freshrss.org/. Blog section is under "News" link. It also adds Atom feeds.

This PR comes with Icomoon font to add some useful icons.

Fix https://github.com/FreshRSS/freshrss.org/issues/8
Fix https://github.com/FreshRSS/freshrss.org/issues/10

### CODE REVIEW

**Comment by marienfressinaud** [comment]
I know I send my PR on the master branch but there is no dev branch for now since I don't find any interest for the moment.

**Comment by aledeg** [comment]
You'll be punished :)

**Comment by aledeg** [comment]
I'd love to merge but I can't. I do not have write access

**Comment by marienfressinaud** [comment]
Oops, sorry about that, it should be ok now!

**Comment by marienfressinaud** [comment]
Thanks! Article will be here tomorrow so we'll be able to announce blog in the same time :).

By the way, I will not be available from 12th March until… probably July! I will be travelling around France and Europe without any computer. I will take a tablet with me so I will be able to review your PR but it will not be in my priorities ;).

**Comment by aledeg** [comment]
OK, so I still have 10 days to make some PR and wish you a nice trip

**Pull request merged**
